title: "Mengyuan (Maggie) Zhang"
description: "Assistant Professor at the VU Amsterdam"
baseurl: ""
url: "https://mengyuanzhang.github.io"

remote_theme: mmistakes/minimal-mistakes

author:
  name: "Mengyuan (Maggie) Zhang"

atom_feed:
  hide: true  

markdown: kramdown
permalink: /:categories/:title/
